//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility_Promus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility_Promus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ind_id&quot;#&quot;ind_nome&quot;#&quot;ind_att_prevalente&quot;#&quot;ind_musicista&quot;#&quot;ind_sesso&quot;#&quot;ind_provenienza&quot;#&quot;ind_note&quot;#&quot;X0VERN&quot;#&quot;XUTEN&quot;#&quot;XDTAGG&quot;
        ///&quot;1&quot;#&quot;Cappelletti, Giovanni Antonio&quot;#&quot;Contralto&quot;#&quot;s&quot;#&quot;m&quot;#&quot;It&quot;#NULL#&quot;2921&quot;#&quot;sysadmin&quot;#&quot;2006-06-01&quot;
        ///&quot;2&quot;#&quot;Bonanni, Ippolito&quot;#&quot;Contralto&quot;#&quot;s&quot;#&quot;m&quot;#&quot;It&quot;#NULL#&quot;3729&quot;#&quot;sysadmin&quot;#&quot;2006-06-01&quot;
        ///&quot;5&quot;#&quot;Adami, Andrea&quot;#&quot;Sopranista&quot;#&quot;s&quot;#&quot;m&quot;#&quot;It&quot;#NULL#&quot;6296&quot;#&quot;maras&quot;#&quot;2006-11-07&quot;
        ///&quot;6&quot;#&quot;Cappelletti, Pier Francesco&quot;#&quot;Maestro di Cappella&quot;#&quot;s&quot;#&quot;m&quot;#&quot;It&quot;#NULL#&quot;7927&quot;#&quot;sysadmin&quot;#&quot;2006-06-01&quot;
        ///&quot;7&quot;#&quot;Cappelletti, [rest of string was truncated]&qu....
        /// </summary>
        internal static string individui__1_ {
            get {
                return ResourceManager.GetString("individui__1_", resourceCulture);
            }
        }
    }
}
